/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: GameplayNarrative.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @GameplayNarrative: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("name", () => this.@name, val => this.@name = val);
			VarDef("health", () => this.@health, val => this.@health = val);
			VarDef("profession", () => this.@profession, val => this.@profession = val);
		}

		public StoryVar @name;
		public StoryVar @health;
		public StoryVar @profession;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@GameplayNarrative()
	{
		this.StartPassage = "start";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Welcome

	void passage1_Init()
	{
		this.Passages[@"Welcome"] = new StoryPassage(@"Welcome", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"[img[https://iiif.lib.ncsu.edu/iiif/0003729/0,0,5985,4075/375,/0/default.jpg]]");
		yield return lineBreak();
		yield return text(@"I walk up to the main campus carrying my cases, ready to begin my year at North Carolina State College of Agriculture and Mechanic Arts. As I step onto the campus and you see a small sign in front of the a large building. A sense of excitement and anticipation fills me as I read:");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hello ");
		yield return text(Vars.name);
		yield return text(@"! We will be providing you a more formal welcome with an information packet and map as you proceed to the administrative building. This building was originally constructed in 1889 and referred to as the Main building but wwas recently renamed Holladay Hall");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I smile at the memory and the long summers spent in fake wars that always ended in elaborate and dramatic death scenes. Now we both were here, sharing a dorm room and forging our paths that we decided so early during those hot summer days. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I need to ");
		yield return link(@"find him soon", @"find him soon", null);
		yield return text(@", as we will be sharing a room this semester.");
		yield return lineBreak();
		yield return lineBreak();
		Vars.health = 60;
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Holladay Hall

	void passage2_Init()
	{
		this.Passages[@"Holladay Hall"] = new StoryPassage(@"Holladay Hall", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0003666/square/300,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"As I enter the main entry for Holladay Hall and see a hive of activity.");
		yield return lineBreak();
		yield return text(@"New and returning students are milling around the stairway leading to the offices and rooms above. Lights hanging above wood parquet flooring illuminate the grand hallway. The walls are papered with notices and posters outlining progress of student organizations, graduating classes, and perhaps most importantly, the war effort.  Several catch my eye:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Victory Gardens!", @"Victory Gardens!", null);
		yield return text(@"  Support the War Effort!");
		yield return lineBreak();
		yield return link(@"Battle the Flu", @"Battle the Flu", null);
		yield return text(@" Kaiser Bill's ally");
		yield return lineBreak();
		yield return link(@"Agricultural Extension", @"Agricultural Extension", null);
		yield return text(@" notices");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I sigh and wonder when this dreadful war will be over. America’s involvement had begun only recently, but it resulted in the fantasies of my youth coming true, at least in part, for good and ill. We, Alex and I will both be soldiers in training, cadets, along with most of the other students on campus.  I am still not thrilled at the propspect, but I understand the need.  Pacisfism didn't work to stop the German machine.  Maybe innovation can.");
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" You turn down a ");
		yield return link(@"long hallway", @"long hallway", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: start

	void passage3_Init()
	{
		this.Passages[@"start"] = new StoryPassage(@"start", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"Gun fire erupts and sounds of violence and screaming rend the air");
		yield return lineBreak();
		Vars.name = "Jimmy";
		yield return lineBreak();
		yield return link(@"I am Shot!", @"I am Shot!", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"I shoot the enemy", @"I shoot the enemy", null);
		yield return lineBreak();
		yield return lineBreak();
		Vars.health = 50;
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: long hallway

	void passage4_Init()
	{
		this.Passages[@"long hallway"] = new StoryPassage(@"long hallway", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"<img src=""http://goodnightraleigh.com/uploaded_images/Hooladay-Hall_1930_1st-floor-hall.jpg"" width=""300px"" height=""400px"">");
		yield return lineBreak();
		yield return text(@"One poster in particular makes you pause: a nurse has her face covered with a mask and warns the viewer the ways in which the flu can be avoided. The rumors of a deadly contagion, the Spanish Flu, reaching the shores of America are frightening. One warning makes you feel better, get fresh air and sunshine.  You are a farmer, no danger there.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Will the flu hit Raleigh?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Another poster catches you eye as you pass by: A picture of a victory garden");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You smile smugly; gardens not only help health and well-being, but help the war effort too.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You turn toward the ");
		yield return link(@"reception", @"reception", null);
		yield return text(@" desk at the end of the hallway");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: reception

	void passage5_Init()
	{
		this.Passages[@"reception"] = new StoryPassage(@"reception", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"You approach the secretary at the admissions desk and greet her.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You notice yet another poster on the wall next to reception ");
		yield return lineBreak();
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0002451/full/350,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"“Hello, madam. My name is ");
		yield return text(Vars.name);
		yield return text(@" and I need to check in and find my dorm room.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"She looks up and smiles politely. She rifles through a set of files on her desk and selects one to hand to you.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Good afternoon, ");
		yield return text(Vars.name);
		yield return text(@", and welcome. Here is an information packet with you new map, assigned room, a key for the room, and instructions for finding your way. A copy of your class schedule is included. Classes will begin officially in two days, but, as I am sure you have already seen, many of the students have already begun preparing for the semester and opening up classrooms and laboratories. Feel free to return here if you have any questions. Watauga Hall is out the front doors, to the right and behind this building. You can’t miss it. If you reach the ");
		yield return link(@"infirmary", @"Next", null);
		yield return text(@", Winslow Hall, you have gone too far.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Thank you for your help""");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Next

	void passage6_Init()
	{
		this.Passages[@"Next"] = new StoryPassage(@"Next", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"Her mention of the infirmary gives you pause.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Thank you.  I saw the poster about the Spanish Flu, and I wondered….”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"She interrupts with a smile. “Not to worry. Get plenty of rest, sunshine, proper nutrition, and, if you believe in that kind of thing, perhaps a vaccination, available at the infirmary, and you will be right as rain.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You smile weakly and turn to go to your new dorm. You did not see Alex, and he was supposed to arrive yesterday to get settled in and then meet you out front.  You realize you have not seen him yet and hope he is all right.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You are tempted to go check out the ");
		yield return link(@"classrooms and laboratories", @"classrooms and laboratories", null);
		yield return text(@", but think better of it and prceed to your dorms");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: Watauga Hall

	void passage7_Init()
	{
		this.Passages[@"Watauga Hall"] = new StoryPassage(@"Watauga Hall", new string[]{ "WH", }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"<img src=""https://i.imgur.com/zboXnD1.jpg"" width=""400px"" height=""400px"" >");
		yield return lineBreak();
		yield return text(@"I enter the front door of Watauga and am greeted by an atmosphere of nervous excitement. Students are moving from one hallway to another, calling out to their friends, and introducing themselves to new faces. I approach the stairs to the upper floors and head up to my room.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I unlock your door and push into the room with your suitcase and welcome packet. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I see Alex sitting on the bed, his head in his hands.  The bed is against a wall with a window centered on it.  ");
		yield return link(@"My bed", @"Your bed", null);
		yield return text(@" is along the opposite wall with a bureau standing along side, waiting to be filled.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Your bed

	void passage8_Init()
	{
		this.Passages[@"Your bed"] = new StoryPassage(@"Your bed", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"<img src=""https://www.lib.ncsu.edu/sites/default/files/files/news/scrc/2015/08/www7-1024x825.jpg"" />");
		yield return lineBreak();
		yield return text(@"“Alex!”  I drop my cases next to the vacant bed and walk over to Alex’s side.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“How are you?  Why didn’t you meet me in front of the building?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Alex doesn’t respond, but sits still on the bed in front of the window.  You approach and notice how pale he looks, and his face glistens with sweat. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Alex?  Are you all right?  What is the matter?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Hello, ");
		yield return text(Vars.name);
		yield return text(@"."" I'm sorry. I’m not really feeling all that well.  I feel a bit shaky and dizzy.  I have been extraordinarily tired today. I’ll be fine.  How was you trip here?"" He asked quickly, obviously wanting to change the subject. """);
		yield return link(@"Was it eventful", @"Was it eventful", null);
		yield return text(@""" He smiled, a little weakly, and sat back against the wall, and drew his knee up to rest his arm.");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: Winslow Hall

	void passage9_Init()
	{
		this.Passages[@"Winslow Hall"] = new StoryPassage(@"Winslow Hall", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		if (Vars.profession == "Doctor")
		{
			yield return text(@" ");
			yield return lineBreak();
			yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0003912/0,0,4463,5709/279,/0/default.jpg"" />");
			yield return lineBreak();
			yield return text(@"You escort Alex to the infirmary, hoping that the nurses there will know how to care for him.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"As I enter the main floor, supporting Alex with my arm under his shoulders, my heart sinks.  The room is sull of the sick!  The nurses and doctors were rushing from one patient to another.  I call one over and give Alex over into her care.    I am now more determined than ever to find out what is wrong with Alex.  Is it this dreadful Spanish flu? Or something more mundane?  ");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"I am going to go to the ");
			yield return link(@"library", @"Yarborough Court", null);
			yield return text(@" and find out");
			yield return lineBreak();
		}
		else
		{
			yield return lineBreak();
			yield return text(@"<img src=""https://www.sanluisobispo.com/news/local/news-columns-blogs/times-past/jekxfe/picture187746438/alternates/FREE_1140/Invalid%20Ward%20Camp%20Funston--Ft.%20Riley%201918"" width=""550px"" height=""400px"">");
			yield return lineBreak();
			yield return text(@"I rush into the infirmary and my heart sinks. I find Alex lying on a cot surrounded by what must be dozens of ill patients. The room is full of the sick!  The nurses and doctors were rushing from one patient to another.  I call one over and I recognize her as the neice of the University Preseident, Eliza Riddick.  Hello ma'am.  I am looking for my freind, Alex.  ");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""He is over there.  He is not doing well. Sit with him and try to cheer him up.  Keeping one's spirits up is as important as anyting we can do.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"I've collected some food and herbs from the garden.  May I give hime those?");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""Of course.""");
			yield return lineBreak();
			yield return text(@"I walk over to Alex and find him only partially conscious.  I add the herbs to the broth and encourage him to drink it.  I wish I could talk to him all I'd learned about proper nutrition, fresh air and exercise, but that will have to wait. ");
			yield return lineBreak();
			yield return text(@"Only time will tell");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@" End", @"Bell Tower", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: Patterson Hall

	void passage10_Init()
	{
		this.Passages[@"Patterson Hall"] = new StoryPassage(@"Patterson Hall", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0004906/0,0,5649,4563/354,/0/default.jpg"" />");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I enter the classrooms and see Jane Mc Kimmon working with some agricultural extension workers.  She looks up and smiles and moves toward me ");
		yield return lineBreak();
		yield return text(@"<img src=""https://www.lib.ncsu.edu/sites/default/files/files/news/scrc/2016/02/mckimmon1939-719x1023.jpg"" width=""300px"" height=""400px"">");
		yield return lineBreak();
		yield return text(@"""Can I help you?""");
		yield return lineBreak();
		yield return text(@"""My firend is ill.  He has a fever and dizziness and seems exhausted""");
		yield return lineBreak();
		yield return text(@"""I am sorry.  How can i help?""");
		yield return lineBreak();
		yield return text(@"""I need some broth perhaps and advice and some strengthening nutritional advice for the next day or so.""");
		yield return lineBreak();
		yield return text(@"She nods and confers with the other faculty there.  They begin talking with me about the ");
		yield return link(@"Victory Garden", @"Victory Garden", null);
		yield return text(@" and the plants grown there.  She also says that meals are made by Ella McGuire in the kitchens of Leazar Hall.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Definitely talk to Ella.  She knows more about natural healing and balanced diets than anyone else I know.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I really feel that Alex needs some fresh air and exercise to put him back on the road to health.  I decide to head over to the ");
		yield return link(@"athletic field area ->SAS Hall", @"athletic field area ->SAS Hall", null);
		yield return text(@" first and see what is offered.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: Victory Garden

	void passage11_Init()
	{
		this.Passages[@"Victory Garden"] = new StoryPassage(@"Victory Garden", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return lineBreak();
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0001057/full/350,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"The victory garden is located in the middle of what appears to be grazing fields.  Several cows graze peacefully in the field but a large section has been fenced off to plant a garden that supplies fresh fruit, vegetables and herbs to help fight the war effort by having students and staff make the university self-sustaining.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Ms Mcguire indicated the herbs would be in the section closes to Patterson Hall and I go there first, hoping for the proper herbs to make Alex some tea and fortify the boroth Ms McGuire is making.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I gather the herbs I need and head to the kitchens to pick up the broth.  I thank MS McGuire and take the new broth and the tea mix to the ");
		yield return link(@"dorms", @"dorms", null);
		yield return text(@" to give to Alex");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #12: Brooks Hall

	void passage12_Init()
	{
		this.Passages[@"Brooks Hall"] = new StoryPassage(@"Brooks Hall", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text(@"<img src=""https://bloximages.newyork1.vip.townnews.com/technicianonline.com/content/tncms/assets/v3/editorial/4/0f/40f92c7a-db7a-11e5-8eef-77e26cea3d9f/56ce866240817.image.jpg"" />");
		yield return lineBreak();
		yield return text(@"I approach the Circulation desk and greet the man standing there.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Hello, my name is """);
		yield return text(Vars.name);
		yield return text(@" and I waas wondering where to find some information.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""I can help you with that?  What are you looking for in particular?""");
		yield return lineBreak();
		yield return lineBreak();
		if (Vars.profession == "Doctor")
		{
			yield return text(@" ");
			yield return lineBreak();
			yield return text(@"""I wanted to look at information on diagonostic symptom of various illnesses. I would also need to see some recent journals on treatments and vaccines.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""Of course!  We have a wonderful library on current and modern treatments and diseases,  We are quite up to date on treatment and curatives.  They are in those ");
			yield return link(@"stacks", @"stacks", null);
			yield return text(@" there,"" he pointed to the area on the Northern corner");
			yield return lineBreak();
			yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0001711/square/300,/0/default.jpg"" width=""400px"" height=""300px"" >");
			yield return lineBreak();
			yield return text(@"""Are there clinical trials going on?  I heard something about that""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""Why yes! The Spanish Flu is running rampant, killing thousands, if not millions, worldide.  A doctor in Boston has developed a vaccine for the influenza viurs, and they are conducting clinical trials here to test it on volunteers.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""How does one sign up to participate?""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""They are still taking applicants until the end of the week""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""My friend is ill, I am not sure with what.  Can he participate?""  ");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""I believe so.  They are testing its efficacy on current patients.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""Thank you!  I will speak to him immediately""");
			yield return lineBreak();
			yield return lineBreak();
		}
		else
		{
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"I'd like some information on proper nutrrition and disease.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"""That would be over in the stacks there,"" he said, pointing to the southern corner.  ");
			yield return lineBreak();
			yield return text(@"<img src=""https://i.pinimg.com/originals/e3/86/49/e386492f2400aefa7f977fbde3bfc0a0.jpg"" />");
			yield return lineBreak();
			yield return text(@"You can also go to ");
			yield return link(@"Patterson Hall", @"Patterson Hall", null);
			yield return text(@" and speak to the agricultural extension workers there.  A Mrs. Jane McKimmon over there would be helpful.  She is a woman, but she has forgotten more than we will ever know about proper diet, nutrition and the like.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"I thank him and go to the stacks first but see quickly that I should speak with Ms. McKimmon and get her expertise.""");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13: Was it eventful

	void passage13_Init()
	{
		this.Passages[@"Was it eventful"] = new StoryPassage(@"Was it eventful", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text(@"“ My trip went well. Stupendously uneventful, I’m afraid.”  You gaze at Alex again and notice him closing his eyes and grimacing, as if in pain.  You don't look all that great.  What can I do to help?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Nothing.  Really.  Jacob arrived home last week and we’ve been staying up late the last week or so catching up.  He has so many amazing stories about France and the trenches.  He’s a real hero.  I am just a little tired”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You nod and wait excitedly.  Jacob is Alex’s older brother who was sent home from the Western front due to illness.  He was kept in the hospital and then Camp Polk for several days before being given leave to visit home before returning to France. He was needed at the front as a trained field medic. Alex admired him greatly and was determined to follow in his footsteps. ");
		yield return lineBreak();
		yield return lineBreak();
		if (Vars.profession == "Farmer")
		{
			yield return text(@" ""The best thing for you, then is some good old fashioned fresh air and susnshine.  I saw a poster earlier that said that even cures the flu!""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"Alex laughs lightly and nods. “All right. Let’s be off.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"You smile and move toward the door  ""Where to? There's a courtyard  that looked pleasant or a line at the infirmary, Winslow Hall that we can investigate, or a Victory Garden, apprently, is somewhere on campus.""");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"Alex sighs, "" I'm pretty tired.  How about the ");
			yield return link(@"courtyard", @"Patterson Hall", null);
			yield return text(@" to start.""");
			yield return lineBreak();
			yield return lineBreak();
		}
		else
		{
			yield return text(@" ""The best thing for you is to get to the infirmary right now!  You need a doctor's care.  I will walk you to ");
			yield return link(@"Winslow Hall", @"Winslow Hall", null);
			yield return text(@" and then do some research see if I can figure out what's wrong.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"Alex smiled wanly. ""All right, doctor"" he tried to joke, ""I'll go, but you just go on.  You must want to look around. and I know you, you will want to go directly to the library.  It's over in Brooks Hall ");
		}
		yield return lineBreak();
		yield break;
	}


	// .............
	// #14: SAS Hall

	void passage14_Init()
	{
		this.Passages[@"SAS Hall"] = new StoryPassage(@"SAS Hall", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text(@"<img src =""https://iiif.lib.ncsu.edu/iiif/0000088/0,0,11925,9619/746,/0/default.jpg"" width=""550px"" height=""400px"" >");
		yield return lineBreak();
		yield return text(@"The field is covered with cadets in uniform beginning traning exercises.  They all look fit and healthy; quite a feat with the illness spreading on campus.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I looks around the field and see a football player warming up near by. It looks like William C. Lee.  He was a fullback and had returned from France only recenlty.  He had fought bravely and now returned to finish his degree and the ROTC program.  He wanted to stay in the army and train soldiers.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I approach him and he nods in my direction. ""Good morning sir,"" I greet him.  ""I wondered if you knew anything about the illness spreading through the students here,  My friend may be ill, and I am trying to treat him.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Probably influenza.  I saw it on the front before I retuned home.  It is a nasty disease.  Physical fitness is the key.  Your body can fight the battle with the proper weapons. "" He nods towards the training students on the field.  ""Train the body and the mind.""  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Thank you, sir.  I will keep that in mind.""  I wander off the field watching the sodiers.  William is right, but I decide that this would be best after Alex is well.  I really should go to the ");
		yield return link(@"kitchens", @"Leazar Hall", null);
		yield return text(@" and get some good food.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #15: you win

	void passage15_Init()
	{
		this.Passages[@"you win"] = new StoryPassage(@"you win", new string[]{ "Alex-Wins", }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text(@"“Unlikely,” I say grinning”  “I’m going to be a soldier!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" “I thought you were going to be a doctor, and heal the wounded.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“I can do both, of course,” I reply scornfully. “I will be an army medic.” I nod and smile proudly. His grandfather had told him stories of great battle medics in the Civil War and the army doctors who saved the lives of soldiers so they would defend their country. “What do you want to be?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" Alex thinks a minute and shrugged. ");
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A Farmer I guess.  I hate fighting, and you always win anyway.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I shake my head mournfully.  “That’s boring. What will you do if someone gets sick way out in the middle of nowhere?”  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“My grandda always said that doctors are quacks. I will be” Alex said more firmly, “and learn how to heal my family with herbs and stuff.  That’s what my gramma used to do.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“You’re going to be a quack?!” I howled in laughter");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“I am not!"" Alex yelled defiantly.  ""Come here. I'll get you!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"The memory fades->Welcome", @"The memory fades->Welcome", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #16: Alex crows in triumph

	void passage16_Init()
	{
		this.Passages[@"Alex crows in triumph"] = new StoryPassage(@"Alex crows in triumph", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text(@"“Not likely,” Alex said grinning”  “I’m going to be a soldier!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" “I thought you were going to be a doctor, and heal the wounded.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“I can do both, of course,” Alex replied scornfully. “I will be an army medic.” Alex nodded and smiled proudly. His grandfather had told him stories of great battle medics in the Civil War and the army doctors who saved the lives of soldiers so they would defend their country. “What do you want to be?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""I'm not sure.  A Doctor, I guess.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Alex shook his head mournfully.  “That’s boring. What will you do if someone needs food in the city.  What are you gonna do,  all you can do is give them medicine!”  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“My grandda always said that farmers are quacks, always making up snake oil. I will be a doctor,” I say more firmly, “and learn how to heal my family with medicines and stuff.  That’s what my gramma used to do.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“You’re going to be a quack?!” Alex howled in laughter”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“I am not!"" I say defiantly.  ""Come here. I’m going to shoot you with my rifle and run you through with my bayonet!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"The memory fades ->Welcome", @"The memory fades ->Welcome", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #17: find him soon

	void passage17_Init()
	{
		this.Passages[@"find him soon"] = new StoryPassage(@"find him soon", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text(@"I finish reading the sign, hoping it will direct me to the right direction.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""The journey you are about to take is a long one but immensely rewarding for you, your family, and your community. As you think of the journey of a university education you smile and think back to the moment you decided to pursue this course, when you played with your childhood friend Alex and planned your future.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I open my acceptance letter and glance once again at the map included and the assignment of the dorm for the next year. Watauga Hall! I smile in anticipation again, and head to the Main Building, ");
		yield return link(@"Holladay Hall", @"Holladay Hall", null);
		yield return text(@" to gather the information I will need to get settled and meet with Alex.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"<img src=""Images/Map 1916.jpg"" />");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #18: Victory Gardens!

	void passage18_Init()
	{
		this.Passages[@"Victory Gardens!"] = new StoryPassage(@"Victory Gardens!", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return lineBreak();
		yield return text(@"<img src=""https://www.washingtonpost.com/rf/image_1484w/2010-2019/WashingtonPost/2011/05/24/LocalLiving/Images/ho-higgins26-victoryBW.jpg?t=20170517"" width=""300px"" height=""400px"">");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #19: Battle the Flu

	void passage19_Init()
	{
		this.Passages[@"Battle the Flu"] = new StoryPassage(@"Battle the Flu", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return lineBreak();
		yield return text(@"<img src =""https://www.laphamsquarterly.org/sites/default/files/images/roundtable/1918main.jpg"" width=""550px"" height=""400px"" >");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #20: Agricultural Extension

	void passage20_Init()
	{
		this.Passages[@"Agricultural Extension"] = new StoryPassage(@"Agricultural Extension", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text(@"[img[""https://iiif.lib.ncsu.edu/iiif/gng00413_001/0,0,4167,6245/261,/0/default.jpg""]]");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #21: classrooms and laboratories

	void passage21_Init()
	{
		this.Passages[@"classrooms and laboratories"] = new StoryPassage(@"classrooms and laboratories", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text(@"I leave the building feeling a little overwhelmed, but excited too.  I wanted to be successful, and that journey had begun. I wander towards Watauga, enjoying the heavy air of a North Carolina summer day and the perfume of the flowers surrounding the building.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I look towards ");
		yield return link(@"Watauga Hall", @"Watauga Hall", null);
		yield return text(@" and decide to head straight there to drop off my bags.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0003223/square/300,/0/default.jpg"" />");
		yield return lineBreak();
		yield return lineBreak();
		if (Vars.profession == "Farmer")
		{
			yield return text(@" ");
			yield return lineBreak();
			yield return text(@"I look around the college buildings that sourround a garden plaza.  I note the infirmary close by but dismiss it for now. I begin making note of the greenhouses and tilled fields in the distance.  This is an agricultural schhol and your new home. I smile in delight.");
			yield return lineBreak();
			yield return lineBreak();
		}
		else
		{
			yield return text(@" ");
			yield return lineBreak();
			yield return text(@"I make note of the infirmary neighboring the dormitory as I pass by, making a mental note to stop in later and get my vaccines and physical. I'd also like to talk to the doctos and nursese on staff.  It is never too early to begin learning the ropes. I smile in satisfaction ");
			yield return lineBreak();
			yield return lineBreak();
		}
		yield return lineBreak();
		yield break;
	}


	// .............
	// #22: Yarborough Court

	void passage22_Init()
	{
		this.Passages[@"Yarborough Court"] = new StoryPassage(@"Yarborough Court", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text(@"""Mister!  Hey Mister!!""");
		yield return lineBreak();
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0004941/square/300,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"I enter a large green courtyard with flowers and grass surrounding a central plaza.  It sits in the center of the few original building on campus.  I see a small girl of about 8 years old playing with jacks in tiled area.  She is waving at me and jumping excitedly.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Mister! Hello mister!  My name is Mary.  May Yarborough.  I will go to college one day and be a famous person!  Maybe a scientist! Hey mister, do you want to play jacks?""");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Yes", @"play jacks", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"No", @"No", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #23: stacks

	void passage23_Init()
	{
		this.Passages[@"stacks"] = new StoryPassage(@"stacks", new string[]{ "Brooks", }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0228522/square/300,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"I head over to the stacks, wondering if I can find any published information on the clinical trials or vaccines in general.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I spend some time readings and cross checking information.  There are so many differing opinions on what Alex may have wrong, not to mention the pros and cons of vaccines.  Some say they save lives and will extend human life.  Others claim they are deadly, far more trouble than they are worth. If it is Spanish Flu that was affecting Alex, it is extremely dangerous.  The flu is deadly in some cases, known for drastic and rapid changes in health and stability.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Alex's syptoms match the flu: dizziness, fever, sweats and exhaustion.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"One thing that occurs everywhere in the literature is that best to assist any treatments with proper nutrition.  I decide my next stop hsould be the kitchens in ");
		yield return link(@"Leazar Hall", @"Leazar Hall", null);
		yield return text(@".  Perhaps I can make some restortive broth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #24: Leazar Hall

	void passage24_Init()
	{
		this.Passages[@"Leazar Hall"] = new StoryPassage(@"Leazar Hall", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text(@"<img src=""https://iiif.lib.ncsu.edu/iiif/0004087/square/300,/0/default.jpg"" />");
		yield return lineBreak();
		yield return text(@"I enter the Kitchens of Leazar Hall and see several women busily preparing food.  One steps forward with a smile and and air of care and concern.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"<img src=""https://i.imgur.com/4SR3Kum.png"" />");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""How can I help, sir?""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"It is Ella Mc Guire, making up some broth for her patients.  She is a legend among the students, calm and caring.  She acts like a mother to many of the men here so homesick for a mother's concern.");
		yield return lineBreak();
		yield return text(@"I've chatted with her before. She told me she was a freed slave who worked most of her young life on a plantations, but came to Raleigh when she was freed.  She is shocked at the Spanish Flu and has been helping as she could with nursing and care.");
		yield return lineBreak();
		yield return lineBreak();
		if (Vars.profession == "Farmer")
		{
			yield return text(@" ");
			yield return lineBreak();
			yield return text(@"I ask her about folk remedies she knows and she describes some recipes for tea that have willow bark for pain and fever.  I ask if she knows about the herbs and she directs me to the ");
			yield return link(@"Victory Garden", @"Victory Garden", null);
			yield return text(@" and I will find what I need.");
			yield return lineBreak();
			yield return lineBreak();
			yield return lineBreak();
		}
		else
		{
			yield return text(@" I ask Ms. McGuire for some special broth that I can take to Alex.  It is important he regain some strength and his natural resistance before he can enter any trial.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text(@"She is kind as she prepares the broth for me to take over.  She offers to put some herbs or other natural remdies, but I refuse. ");
			yield return lineBreak();
			yield return text(@"""Thank you, but no.  If he does enter the trial, I wouldn't want to interfere with that.""");
			yield return lineBreak();
			yield return text(@"I leave the kitchens and head to the ");
			yield return link(@"infirmary", @"Winslow Hall 2", null);
			yield return text(@" ");
			yield return lineBreak();
			yield return lineBreak();
		}
		yield return lineBreak();
		yield break;
	}


	// .............
	// #25: Winslow Hall 2

	void passage25_Init()
	{
		this.Passages[@"Winslow Hall 2"] = new StoryPassage(@"Winslow Hall 2", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text(@"<img src=""https://www.sanluisobispo.com/news/local/news-columns-blogs/times-past/jekxfe/picture187746438/alternates/FREE_1140/Invalid%20Ward%20Camp%20Funston--Ft.%20Riley%201918"" width=""550px"" height=""400px"">");
		yield return lineBreak();
		yield return text(@"You enter the cot strewn first floor and wind your way through cots lined from one end to the other.  You frown as you look at there patients; who will help them?  You find Alex and deliver the broth Ms McGuire gave you.  He is only partially conscious but you are able to give him some broth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I wish I could discuss the clinical trials and the the advantages of various treatments but that will ahve to wait");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Only time will tell now.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"End ", @"Bell Tower", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #26: dorms

	void passage26_Init()
	{
		this.Passages[@"dorms"] = new StoryPassage(@"dorms", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text(@"Ireturn to Watauga Hall with a spring in my step.  I know what I have brought will heal Alex.  ");
		yield return lineBreak();
		yield return text(@"As I enter our room, I start to panic.  Alex is gone!  I grab another student and ask where Alex went.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Alex took a turn for the worse and we took him to the infirmary.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Thanks!"" I say as i dart back out and run over to the ");
		yield return link(@"Winslow Hall", @"Winslow Hall", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #27: Bell Tower

	void passage27_Init()
	{
		this.Passages[@"Bell Tower"] = new StoryPassage(@"Bell Tower", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text(@"<img src=Images/""Memorial Tower 2.jpg"" />");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #28: play jacks

	void passage28_Init()
	{
		this.Passages[@"play jacks"] = new StoryPassage(@"play jacks", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text(@" I smile in amusement and cover a laugh with a small cough.  ""Of course poppet, but I can't play long.  I need to go to the library."" I play jacks for a bit, and then sit up.");
		yield return lineBreak();
		yield return text(@"""Thanks for the game, Mary but I should get on.""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Ok, thanks mister.  Hey Mister!  don't go near the library. I hear there was a trial going on!  I wonder what he did wrong! Maybe murder!""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Trial?""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Yes, they said it was a trial where they shoot people! A pineapple trial""");
		yield return lineBreak();
		yield return text(@" I stare at her bemused and then it strikes me ");
		yield return link(@"""A clinical trial?""", @"Brooks Hall", null);
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" ""Yeah that's it. They said they were gonna shoot people with stuff in the garden.""");
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" I cough again to smother a laugh and nod seriously. ""A clinical trial.  I will be careful.  Thanks, Mary""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #29: I am Shot!

	void passage29_Init()
	{
		this.Passages[@"I am Shot!"] = new StoryPassage(@"I am Shot!", new string[]{ "Farmer1", }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" “Alex! I’ve got you!  Bang Bang!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" I grin, ""No! I've got you!  I pulled out my pistol first!""  Bang Bang!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"“Arrrrrrg! “ Alex falls to the ground theatrically and you laugh delightedly. """);
		yield return link(@"you win", @"you win", null);
		yield return text(@" this time, but I will get my revenge the next battle we have!""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" ");
		Vars.profession = "farmer";
		yield return lineBreak();
		yield break;
	}


	// .............
	// #30: I shoot the enemy

	void passage30_Init()
	{
		this.Passages[@"I shoot the enemy"] = new StoryPassage(@"I shoot the enemy", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return lineBreak();
		yield return text(@"Alex neatly ducks the shot and points his rifle at you. ""Bang Bang!"" I stop in my tracks and clutch my chest. ""Arrrrrrg.""  I fall dramatically to the ground and start convulsing grotesquely.  ");
		yield return link(@"Alex crows in triumph", @"Alex crows in triumph", null);
		yield return text(@" as he laughs. ""I win!  I win!""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I smile and stop my death spasms and sit up. ""Maybe you won this time, but not for long!""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		yield return text(@" ");
		yield return lineBreak();
		Vars.profession = "doctor";
		yield return lineBreak();
		yield break;
	}


	// .............
	// #31: No

	void passage31_Init()
	{
		this.Passages[@"No"] = new StoryPassage(@"No", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text(@"""Not now little girl.  I am very busy.  Maybe later""");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Ok, mister,"" she says looking dejected.  ""But be carefule near the library!""  she skips off before you can question her furhter.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You proceed to the ");
		yield return link(@"Library", @"Brooks Hall", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


}