/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OldProjectNarrative.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OldProjectNarrative: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@OldProjectNarrative()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return htmlTag("<img src=\"Images/Holladay Hall.jpg\" />");
		yield return lineBreak();
		yield return text("Hello New student!  We welcome you to the administrative building.  This building was orginally constructed in 1889 and referred to as the Main building but would be named Holladay Hall. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You can now go to your assigned dorm building, ");
		yield return link("Watauga Hall", "Watauga Hall", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return text("NC State was established under the auspices of the federal Morrill Act of 1862, which allowed the U.S. government to donate federally owned land to the states for the purpose of establishing colleges that would teach “agriculture and the mechanic arts.” The brand-new school held its first classes in the fall of 1889 with 72 students, six faculty members and one building, Hollday Hall. THe next stop highlights the development of the university in terms of residence halls and education ");
		yield return link("Watauga Hall", "Watauga Hall", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return text("When North Carolina State University (NCSU) was founded in 1887, the school embodied ideals that were rapidly transforming the field of higher education. Chief among them was the belief that colleges should not be reserved for a select few and that the children of farmers, mechanics and other workers should have access to the opportunities and benefits of higher education. A new generation of progressive thinkers founded the college, known then as the North Carolina College of Agriculture and Mechanic Arts. ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Watauga Hall

	void passage2_Init()
	{
		this.Passages[@"Watauga Hall"] = new StoryPassage(@"Watauga Hall", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("This five-story Watauga Hall was built in 1896.  This structure you see today is actually the second version of this building. The first was destroyed by fire in 1901, during Thanksgiving weekend. With the help of students who kept it wet enough to save it, nearby Holladay Hall survived the fire, despite the fact that the heat could be felt as far as Hillsborough Street. ");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("	");
		yield return htmlTag("<img src=\"Images/Watauga Hall.jpg\" />");
		yield return lineBreak();
		yield return text("	");
		yield return htmlTag("<img src=\"Images/watauga Hall renovated.jpg\" />");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("	You walk further into the building and find your room and your roommate,   Alexander Holladay Pickell, grandson of the innagural president of NC State, Alexander Haolladay, and the person for whom the Main Administrative building was named.");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("You place your belining along one bed and turn to find your roommate and check in.	");
		yield return lineBreak();
		yield return text("	Alex is very sick!  He appears to be fevered and pale.  He is incoherant and appears to be in pain.  You begin thinking quickly: \"How do I help him?\"");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("	You seem to have two choices. There is no way to tell what is better, but you must make the decision quickly.  Alex is sick and needs help.  You can go:");
		yield return lineBreak();
		yield return text("	1) ");
		yield return link("Winslow Hall", "Winslow Hall", null);
		yield return text(" and the nirses and mediacl staff there can provide him with a new experimnetal vaccine that might help him, but may also be dangerous.");
		yield return lineBreak();
		yield return text("	2) ");
		yield return link("SAS Hall", "SAS Hall", null);
		yield return text(" where holistic natural medicine is explored as well as physical fitness, proper nutrition and cooking techniques are explored.  This path is safer but perhaps too long term to save your roommate. ");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("	FUN FACTS:");
		yield return lineBreak();
		yield return text("		The site was built in a restrained Romanesque Revival style, and became the site of numerous pranks. According to one story, a cannon that stood in front of the ");
		yield return link("1911 building", "1911 building", null);
		yield return text(", located at the end of the grassy Court of the Carolinas, was found one morning reassembled on Watauga's roof. On another occasion, a mule had been led up several flights of stairs to the top floor. One story is that the mule had to be blindfolded to be led down; another is that they had to lower the mule by sling and rope from an upper story window. ");
		yield return lineBreak();
		yield return text("			");
		yield return lineBreak();
		yield return text("	The pranks are examples of the friendly but stiff competition that still exists between the engineering and agriculture students of the University's main two departments. ");
		yield break;
	}


	// .............
	// #3: Winslow Hall

	void passage3_Init()
	{
		this.Passages[@"Winslow Hall"] = new StoryPassage(@"Winslow Hall", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Winslow Hall was first used as the student Health center.  This was also an infirmary for ill students.  Vaccines and innoculations were administered here and its would have been the location for clinical trials for influenza vaccines.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("For further information you can go to ");
		yield return link("Brooks Hall", "Brooks Hall", null);
		yield return text(", the location of the original library for the campus.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(" While walking towars the library, you can also stop by ");
		yield return link("Mary Yarborough Court", "Mary Yarborough Court", null);
		yield break;
	}


	// .............
	// #4: SAS Hall

	void passage4_Init()
	{
		this.Passages[@"SAS Hall"] = new StoryPassage(@"SAS Hall", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("The building you see in front of you is very new.  It was built to house Mathematics and statistics in 2009. The 119,000 square foot building houses state-of-the-art classrooms, computer labs, tutorial centers and meeting and study space for students and faculty from NC State's mathematics and statistics departments.");
		yield return lineBreak();
		yield return htmlTag("<img src=\"Images/Riddick Field ROTC.jpg\" />");
		yield return lineBreak();
		yield return htmlTag("<img src=\"Images/Campus Map.jpg\" />");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The land beneath the building was once the first athletic field on campus. It ws comprised of both a baseball and football fields.  It remained in that location until another field was constructed in 1966.");
		yield return lineBreak();
		yield return htmlTag("<img src=\"Images/Technician article.png\" />");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("This was of the loci for the adminsitration's push to train students in body as well as mind.  The progressive era of the early twentieth cenutry began a more indepth investiagation of all aspects of health and wellness, from medicine to nutrition to rpoper storage, canning and food preservation and cooking.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The best way to proceed is to understand nutrition and food, wel will proceed to ");
		yield return link("Patterson Hall", "Patterson Hall", null);
		yield return text(", the location of the hub fot the Agricultural Extension Program");
		yield return lineBreak();
		yield return text("On the way, make sure to look for the ");
		yield return link("Victory Garden", "Victory Garden", null);
		yield return text(" on the green.");
		yield break;
	}


	// .............
	// #5: 1911 building

	void passage5_Init()
	{
		this.Passages[@"1911 building"] = new StoryPassage(@"1911 building", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #6: Patterson Hall

	void passage6_Init()
	{
		this.Passages[@"Patterson Hall"] = new StoryPassage(@"Patterson Hall", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Go back to the Dorm ");
		yield return link("Watauga Hall", "Watauga Hall", null);
		yield return text(" and care for Alex with your new found knwledge.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The illness is over, proceed to the ");
		yield return link("Memorial Bell Tower", "Memorial Bell Tower", null);
		yield return text(" to think about all that has happened");
		yield break;
	}


	// .............
	// #7: Brooks Hall

	void passage7_Init()
	{
		this.Passages[@"Brooks Hall"] = new StoryPassage(@"Brooks Hall", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Brooks hall was the first location of the campus library");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("It seems like even vaccines may need help by maintain proper nutrition.  Look for the ");
		yield return link("Victory Garden", "Victory Garden", null);
		yield return text(" in the fields nearby.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alex has passed away, you go to the ");
		yield return link("Memorial Bell Tower", "Memorial Bell Tower", null);
		yield return text(" to meorialize him");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alex has survived!, you are grateful but realize many others didn't.  GO to the ");
		yield return link("Memorial Bell Tower", "Memorial Bell Tower", null);
		yield return text(" to pay respects to those like Eliza who passed away.");
		yield break;
	}


	// .............
	// #8: Mary Yarborough Court

	void passage8_Init()
	{
		this.Passages[@"Mary Yarborough Court"] = new StoryPassage(@"Mary Yarborough Court", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Proceed back to the library at ");
		yield return link("Brooks Hall", "Brooks Hall", null);
		yield return text(" or move back to ");
		yield return link("Winslow Hall", "Winslow Hall", null);
		yield return text(" to check on Alex");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: Victory Garden

	void passage9_Init()
	{
		this.Passages[@"Victory Garden"] = new StoryPassage(@"Victory Garden", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #10: Memorial Bell Tower

	void passage10_Init()
	{
		this.Passages[@"Memorial Bell Tower"] = new StoryPassage(@"Memorial Bell Tower", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}