/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: TEST.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @TEST: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("reputation", () => this.@reputation, val => this.@reputation = val);
		}

		public StoryVar @reputation;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@TEST()
	{
		this.StartPassage = "Test";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Test

	void passage1_Init()
	{
		this.Passages[@"Test"] = new StoryPassage(@"Test", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("bye nerds");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Clicck", "Test 2", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #2: Test 2

	void passage2_Init()
	{
		this.Passages[@"Test 2"] = new StoryPassage(@"Test 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Hello");
		yield return lineBreak();
		Vars.reputation  = 1;
		yield return lineBreak();
		yield return text("Your current reputation is ");
		yield return text(Vars.reputation);
		yield return lineBreak();
		yield return lineBreak();
		yield return passage("Teest 3");
		yield break;
	}


	// .............
	// #3: Teest 3

	void passage3_Init()
	{
		this.Passages[@"Teest 3"] = new StoryPassage(@"Teest 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("You die now");
		yield return lineBreak();
		yield break;
	}


}