/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Test1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Test1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Test1()
	{
		this.StartPassage = "Test";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Test

	void passage1_Init()
	{
		this.Passages[@"Test"] = new StoryPassage(@"Test", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hello World");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("New Page", "New Page", null);
		yield break;
	}


	// .............
	// #2: New Page

	void passage2_Init()
	{
		this.Passages[@"New Page"] = new StoryPassage(@"New Page", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You will be redirected.");
		yield break;
	}


}